let pagePath = {
  projectConfig: '/create/projectConfig',
  scriptConfig: '/create/scriptConfig',
  jarPackage: '/create/jarPackage',
  dataSource: '/create/dataSource',
  config: '/configInterface/config',
  case: '/caseInterface/case',
  scene: '/sceneInterface/scene',
  task: '/taskInterface/task',
  tool: '/toolInterface/tool',
  httpRunner: '/httpRunnerTest/httpRunner',
  webUiConfig: '/webUiCase/webUiConfig',
  page: '/webUiCase/page',
  element: '/webUiCase/element',
  step: '/webUiCase/step',
  webUiCase: '/webUiCase/webUiCase',
  uiCaseResult: '/webUiCase/uiCaseResult',
  webUiTask: '/webUiCase/webUiTask',
  etlCaseList: '/etl/etlCaseList',
  etlBatchCaseList: '/etl/etlBatchCaseList',
  etlSceneList: '/etl/etlSceneList',
  resultDetailList: '/etl/resultDetailList',
  etlResultList: '/etl/etlResultList'
};

let pageName = {
  ProjectConfig: '项目配置',
  ScriptConfig: '代码脚本',
  JarPackage: 'JAR包管理',
  DataSource: '数据源管理',
  Config: '配置模块',
  Case: '测试用例',
  Scene: '测试场景',
  Task: '任务配置',
  Tool: '小工具',
  HttpRunner: 'HttpRunner',
  WebUiConfig: '配置信息',
  Page: '业务管理',
  Element: '元素管理',
  Step: '步骤管理',
  WebUiCase: '用例管理',
  UiCaseResult: '测试结果',
  WebUiTask: '定时任务',
  ETLCaseList: 'ETL用例',
  ETLSceneList: 'ETL场景',
  ETLBatchCaseList: '批量执行',
  ETLResultDetailList: '用例结果',
  ETLResultList: '结果总览'
};
export { pagePath, pageName };
